name = "dreamlab-auth-api"
compatibility_date = "2024-12-01"
main = "index.ts"

[[d1_databases]]
binding = "DB"
database_name = "dreamlab-auth"
database_id = "e3981999-e8f0-4c07-9e4b-2e50859b8524"

[[kv_namespaces]]
binding = "SESSIONS"
id = "901345296c2848788066686aa67d5909"

[[kv_namespaces]]
binding = "POD_META"
id = "8ec8759ab40d4709a831bf6b0e5241eb"

[[r2_buckets]]
binding = "PODS"
bucket_name = "dreamlab-pods"

[vars]
RP_ID = "dreamlab-ai.com"
RP_NAME = "DreamLab Community"
EXPECTED_ORIGIN = "https://dreamlab-ai.com"
